# Generated by Django 5.0.2 on 2024-02-09 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория животных',
                'verbose_name_plural': 'Название категорий животных',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('other_name', models.CharField(max_length=100, verbose_name='Кличка животного')),
                ('age', models.IntegerField(verbose_name='Возраст животного')),
                ('description', models.TextField(verbose_name='Описание проблемы животного')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_categories', to='api.categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
